language: node_js
node_js:
  - 14.15.5

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run
before_script:
  - echo "nothing to run"

script:
  - docker --version # print docker version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed wjenkins3/udagram-api-feed:v1
  - docker tag udagram-api-user wjenkins3/udagram-api-user:v1
  - docker tag udagram-api-frontend wjenkins3/udagram-api-frontend:v1
  - docker tag udagram-api-reverseproxy wjenkins3/udagram-api-reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push wjenkins3/udagram-api-feed:v1
  - docker push wjenkins3/udagram-api-user:v1
  - docker push wjenkins3/udagram-api-frontend:v1
  - docker push wjenkins3/udagram-api-reverseproxy:v1