apiVersion: v1
kind: Secret
metadata:
  name: env-secret
data:
  POSTGRES_USERNAME: __INSERT_POSTGRES_USERNAME__BASE64____
  POSTGRES_PASSWORD: __INSERT_POSTGRES_PASSWORD__BASE64____
  JWT_SECRET: __INSERT_JWT_SECRET__BASE64____
type: Opaque